"""Add ZOM EdgeNode and FileShard tables

Revision ID: 3631424c28df
Revises: 443425ea62a3
Create Date: 2026-06-17 18:41:06.851531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3631424c28df'
down_revision: Union[str, Sequence[str], None] = '443425ea62a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Sirf Nayi tables banane ka code yahan hona chahiye
    op.create_table('edge_nodes',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('tenant_id', sa.String(), nullable=False),
        sa.Column('device_id', sa.String(), nullable=True),
        sa.Column('ip_address', sa.String(), nullable=True),
        sa.Column('device_type', sa.String(), nullable=True),
        sa.Column('total_storage_mb', sa.Float(), nullable=True),
        sa.Column('available_storage_mb', sa.Float(), nullable=True),
        sa.Column('health_score', sa.Float(), nullable=True),
        sa.Column('is_online', sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_edge_nodes_device_id'), 'edge_nodes', ['device_id'], unique=True)
    op.create_index(op.f('ix_edge_nodes_id'), 'edge_nodes', ['id'], unique=False)
    op.create_index(op.f('ix_edge_nodes_tenant_id'), 'edge_nodes', ['tenant_id'], unique=False)

    op.create_table('file_shards',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('tenant_id', sa.String(), nullable=False),
        sa.Column('original_file_id', sa.String(), nullable=True),
        sa.Column('shard_index', sa.Integer(), nullable=True),
        sa.Column('node_id', sa.Integer(), nullable=False),
        sa.Column('is_safe', sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(['node_id'], ['edge_nodes.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_shards_id'), 'file_shards', ['id'], unique=False)
    op.create_index(op.f('ix_file_shards_original_file_id'), 'file_shards', ['original_file_id'], unique=False)
    op.create_index(op.f('ix_file_shards_tenant_id'), 'file_shards', ['tenant_id'], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buckets',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('buckets_project_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('buckets_pkey'))
    )
    op.create_index(op.f('ix_buckets_tenant_id'), 'buckets', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_buckets_id'), 'buckets', ['id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('region', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('projects_pkey'))
    )
    op.create_index(op.f('ix_projects_tenant_id'), 'projects', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_projects_name'), 'projects', ['name'], unique=False)
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_table('instances',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('vcpu', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('memory_gb', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('instances_project_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('instances_pkey'))
    )
    op.create_index(op.f('ix_instances_tenant_id'), 'instances', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_instances_id'), 'instances', ['id'], unique=False)
    # ### end Alembic commands ###
