"""Initial Snapshot

Revision ID: a3d07166846f
Revises: 
Create Date: 2026-06-08 19:11:36.219322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3d07166846f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_store_items_barcode'), table_name='store_items')
    op.drop_index(op.f('ix_store_items_id'), table_name='store_items')
    op.drop_index(op.f('ix_store_items_name'), table_name='store_items')
    op.drop_table('store_items')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('store_items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('barcode', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('store_items_pkey'))
    )
    op.create_index(op.f('ix_store_items_name'), 'store_items', ['name'], unique=False)
    op.create_index(op.f('ix_store_items_id'), 'store_items', ['id'], unique=False)
    op.create_index(op.f('ix_store_items_barcode'), 'store_items', ['barcode'], unique=True)
    # ### end Alembic commands ###
